version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5020
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db;Database=SurvivalSchool1;User Id=SA;Password=Password_123;MultipleActiveResultSets=true;
    ports:
      - "5020:5020"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Password_123"
      - "ACCEPT_EULA=Y"
    container_name: mssql2
    ports:
      - "1555:1433"
